// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test', async function() {
    await driver.get("http://automationpractice.com/index.php")
    await driver.manage().window().setRect(1382, 744)
    await driver.findElement(By.id("search_query_top")).click()
    await driver.findElement(By.id("search_query_top")).sendKeys("chiffon dress")
    await driver.findElement(By.name("submit_search")).click()
    await driver.findElement(By.css(".ajax_block_product:nth-child(1) .replace-2x")).click()
    await driver.findElement(By.id("group_1")).click()
    {
      const dropdown = await driver.findElement(By.id("group_1"))
      await dropdown.findElement(By.xpath("//option[. = 'M']")).click()
    }
    await driver.findElement(By.css("option:nth-child(2)")).click()
    await driver.findElement(By.id("color_15")).click()
    await driver.findElement(By.css(".exclusive > span")).click()
  })
})